defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: Students
  password: 123456
  socket: /var/run/mysqld/mysqld.sock
development:
  <<: *defaults
  database: weeklysocial_development
test:
  <<: *defaults
  database: weeklysocial_test
production:
  <<: *defaults
  database: weeklysocial_production